### ISSUE TITLE
Remove internal constructor and allow nullability

### ISSUE THREAD

**Issue by GautierLouis** [at-internet/piano-analytics-android#16]
We are using Piano SDK as our main analytics tool.

We created a decorator to fit our needs as follow : 

```
data class Event(val type: String, val properties: Map<String, Any?>)

class TrackingEvent() {

    fun track(event: Event) {
        PianoAnalytics.getInstance().sendEvents(...)
    }
}
```

Sadly, when it comes to map our `Event` to your `Event.Builder()` we encountered two pain points : 

1. Property class only exposes "typed constructors" and hides the one with `Any`
2. Property class  doesn't allow nullable values. Which is allowed in iOS SDK and Javascript SDK

Suggested modifications : 

1. Remove `internal` keyword from `Property` constructor
2. Make `value` of type `Any` nullable

Both of this has a workaround, so it's fine. But it will be great if you can take that changes into consideration

**Comment by DeKaN** [comment]
Hi @GautierLouis ,
1. Property class allows only a subset of types, that are supported by backend and can be converted to JSON. So, we can't allow passing `Any`. 
2. Backend doesn't allow null values for properties, so SDK explicitly denies providing null instead of implicit filtering

**Comment by GautierLouis** [comment]
Hi @DeKaN 

I've understand.

The one thing is : Why with iOS, there is no need to cast out Map<String, Any> to a `Property` (their SDK allow sending a Map<String, Any>) ?. They might deal with Any and nullability on their side and this is all I asked :)

**Comment by DeKaN** [comment]
@MehdiBrahmi 
`Any` without custom json adapter can't be serialized only to `{}`. I think it's not what you want. If you want to use json as property value, you can always serialize your custom object (because you know what fields should be serialized) to json string

@GautierLouis 
SDK for iOS hasn't introduced stricter API yet. But for Android we check [rules](https://developers.atinternet-solutions.com/piano-analytics/data-collection/how-to-send-events/collection-api#property-key-rules) explicitly on `Property` initialization, instead of implicit drop at backend

**Comment by GautierLouis** [comment]
Thanks for your feedbacks.

Ok, well. I guess I have to deal with that.
